# Generated by Django 4.1.7 on 2023-02-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('bhk_type', models.IntegerField()),
                ('gender_preference', models.CharField(max_length=255)),
                ('rental_type', models.CharField(max_length=255)),
                ('furnish', models.CharField(max_length=255)),
                ('mobile_number', models.BigIntegerField()),
                ('mobile_post', models.BooleanField(default=False)),
                ('budget_range', models.BigIntegerField()),
            ],
        ),
    ]
