# Generated by Django 4.1.7 on 2023-02-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_flat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flatmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('bhk_type', models.IntegerField()),
                ('gender_preference', models.CharField(max_length=255)),
                ('rental_type', models.CharField(max_length=255)),
                ('furnish', models.CharField(max_length=255)),
                ('rent', models.BigIntegerField()),
                ('mobile_number', models.BigIntegerField()),
                ('mobile_post', models.BooleanField(default=False)),
                ('amenities', models.CharField(max_length=255)),
            ],
        ),
    ]
